### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is functional only in Security & Compliance Center PowerShell. For more information, see [Security & Compliance Center PowerShell](https://docs.microsoft.com/powershell/exchange/scc-powershell).

  Use the Get-AuditConfigurationRule cmdlet to view audit configuration rules.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://docs.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AuditConfigurationRule [[-Identity] <ComplianceRuleIdParameter>]

   [-DomainController <Fqdn>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-AuditConfigurationRule | Format-List Name,Workload,AuditOperation,Policy
  description: |-
    This example lists summary information about all audit configuration rules.
  summary: ""
- title: Example 2
  code: |-
    Get-AuditConfigurationRule 989a3a6c-dc40-4fa4-8307-beb3ece992e9
  description: |-
    This example lists details about the audit configuration rule named 989a3a6c-dc40-4fa4-8307-beb3ece992e9.
  summary: ""
parameters:
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: DomainController
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="ComplianceRuleIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The Identity parameter specifies the audit configuration rule that you want to view. The name of the rule is a GUID value. For example, 989a3a6c-dc40-4fa4-8307-beb3ece992e9.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Exchange Online
  - Security & Compliance Center
  parameterValueGroup: ""
applicable:
- Exchange Online
- Security & Compliance Center
uid: ExchangePowerShell.Get-AuditConfigurationRule
name: Get-AuditConfigurationRule
description: |-
  To use this cmdlet in Security & Compliance Center PowerShell, you need to be assigned permissions. For more information, see [Permissions in the Microsoft 365 compliance center](https://docs.microsoft.com/microsoft-365/compliance/microsoft-365-compliance-center-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://docs.microsoft.com/powershell/module/exchange/get-auditconfigurationrule
  applicable: Exchange Online, Security & Compliance Center
  title: Get-AuditConfigurationRule
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
