### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available only in Security & Compliance Center PowerShell. For more information, see [Security & Compliance Center PowerShell](https://docs.microsoft.com/powershell/exchange/scc-powershell).

  Use the Set-PolicyConfig cmdlet to modify the endpoint restrictions that are configured in the organization.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://docs.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-PolicyConfig [[-Identity] <OrganizationIdParameter>]

   [-CaseHoldPolicyLimit <Int32>]

   [-ClassificationScheme <ClassificationScheme>]

   [-ComplianceUrl <String>]

   [-Confirm]

   [-DocumentIsUnsupportedSeverity <RuleSeverity>]

   [-EnableLabelCoauth <Boolean>]

   [-EnableSpoAipMigration <Boolean>]

   [-EndpointDlpGlobalSettings <PswsHashtable[]>]

   [-EndpointDlpGlobalSettingsPsws <PswsHashtable[]>]

   [-ExtendTeamsDlpPoliciesToSharePointOneDrive <Boolean>]

   [-OnPremisesWorkload <Workload>]

   [-ProcessingLimitExceededSeverity <RuleSeverity>]

   [-PurviewLabelConsent <Boolean>]

   [-ReservedForFutureUse <Boolean>]

   [-RetentionForwardCrawl <Boolean>]

   [-RuleErrorAction <PolicyRuleErrorAction>]

   [-SenderAddressLocation <PolicySenderAddressLocation>]

   [-WhatIf]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    {{ Add example code here }}
  description: |-
    {{ Add example description here }}
  summary: ""
parameters:
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: CaseHoldPolicyLimit
  description: |+
    {{ Fill CaseHoldPolicyLimit Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="ClassificationScheme" data-throw-if-not-resolved="False" />
  name: ClassificationScheme
  description: |+
    {{ Fill ClassificationScheme Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: Default, V0_AggregatedOnly, V1_DetailedResults
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ComplianceUrl
  description: |+
    {{ Fill ComplianceUrl Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    The Confirm switch specifies whether to show or hide the confirmation prompt. How this switch affects the cmdlet depends on if the cmdlet requires confirmation before proceeding.

    - Destructive cmdlets (for example, Remove-\* cmdlets) have a built-in pause that forces you to acknowledge the command before proceeding. For these cmdlets, you can skip the confirmation prompt by using this exact syntax: -Confirm:$false.
    - Most other cmdlets (for example, New-\* and Set-\* cmdlets) don't have a built-in pause. For these cmdlets, specifying the Confirm switch without a value introduces a pause that forces you acknowledge the command before proceeding.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="RuleSeverity" data-throw-if-not-resolved="False" />
  name: DocumentIsUnsupportedSeverity
  description: |+
    {{ Fill DocumentIsUnsupportedSeverity Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: Low, Medium, High, None, Informational, Information
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableLabelCoauth
  description: |+
    {{ Fill EnableLabelCoauth Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableSpoAipMigration
  description: |+
    {{ Fill EnableSpoAipMigration Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: EndpointDlpGlobalSettings
  description: |+
    The EndpointDlpGlobalSettings parameter specifies the global endpoints. This parameter uses the following syntax: `@(@{"Setting"="<Setting>"; "Value"="<Value>}",@{"Setting"="<Setting>"; "Value"="<Value>"},...)`.

    The value of `<Setting>` is one of the supported values.

    Example values:

    - `@{"Setting"="PathExclusion"; "Value"="C:\Windows";}`
    - `@{"Setting"="PathExclusion"; "Value"="%AppData%\Mozilla";}`
    - `@{"Setting"="PathExclusion"; "Value"="C:\Users\*\Desktop";}`
    - `@{"Setting"="UnallowedApp"="Notepad ++;"Executable"="notepad++"}`
    - `@{"Setting"="UnallowedApp"="Executable"="cmd"}`
    - `@{"Setting"="UnallowedBrowser"="Chrome";"Executable"="chrome"}`
    - `@{"Setting"="CloudAppRestrictions"="Allow"}`
    - `@{"Setting"="CloudAppRestrictionList"="1.1.2.2"}`
    - `@{"Setting"="CloudAppRestrictionList"="subdomain.com"}`
    - `@{"Setting"="CloudAppRestrictionList"="another.differentdomain.edu"}`
    - `@{"Setting"="ShowEndpointJustificationDropdown"; "True";}`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="PswsHashtable" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: EndpointDlpGlobalSettingsPsws
  description: |+
    {{ Fill EndpointDlpGlobalSettingsPsws Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: ExtendTeamsDlpPoliciesToSharePointOneDrive
  description: |+
    {{ Fill ExtendTeamsDlpPoliciesToSharePointOneDrive Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="OrganizationIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    {{ Fill Identity Description }}

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="Workload" data-throw-if-not-resolved="False" />
  name: OnPremisesWorkload
  description: |+
    {{ Fill OnPremisesWorkload Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: None, Exchange, SharePoint, Intune, OneDriveForBusiness, PublicFolder, SharePointOnPremises, ExchangeOnPremises, AuditAlerting, Skype, ModernGroup, DynamicScope, Teams, UnifiedAuditAzure, EndpointDevices, ThirdPartyApps, OnPremisesScanner
- type: <xref href="RuleSeverity" data-throw-if-not-resolved="False" />
  name: ProcessingLimitExceededSeverity
  description: |+
    {{ Fill ProcessingLimitExceededSeverity Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: Low, Medium, High, None, Informational, Information
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: PurviewLabelConsent
  description: |+
    {{ Fill PurviewLabelConsent Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: ReservedForFutureUse
  description: |+
    {{ Fill ReservedForFutureUse Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RetentionForwardCrawl
  description: |+
    {{ Fill RetentionForwardCrawl Description }}

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
- type: <xref href="PolicyRuleErrorAction" data-throw-if-not-resolved="False" />
  name: RuleErrorAction
  description: |+
    The RuleErrorAction parameter specifies what to do if an error is encountered during the evaluation of the rule. Valid values are:

    - Ignore
    - RetryThenBlock (This is the default value)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: Ignore, RetryThenBlock
- type: <xref href="PolicySenderAddressLocation" data-throw-if-not-resolved="False" />
  name: SenderAddressLocation
  description: |+
    The SenderAddressLocation parameter specifies where to look for sender addresses in conditions and exceptions that examine sender email addresses. Valid values are:

    - Header: Only examine senders in the message headers (for example, the From, Sender, or Reply-To fields). This is the default value.
    - Envelope: Only examine senders from the message envelope (the MAIL FROM value that was used in the SMTP transmission, which is typically stored in the Return-Path field).
    - HeaderOrEnvelope: Examine senders in the message header and the message envelope.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Security & Compliance Center
  parameterValueGroup: Header, Envelope, HeaderOrEnvelope
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    The WhatIf switch doesn't work in Security & Compliance Center PowerShell.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Security & Compliance Center
  parameterValueGroup: ""
applicable:
- Security & Compliance Center
uid: ExchangePowerShell.Set-PolicyConfig
name: Set-PolicyConfig
description: |-
  To use this cmdlet in Security & Compliance Center PowerShell, you need to be assigned permissions. For more information, see [Permissions in the Microsoft 365 compliance center](https://docs.microsoft.com/microsoft-365/compliance/microsoft-365-compliance-center-permissions).
metadata:
  external help file: Microsoft.Exchange.TransportMailflow-Help.xml
  online version: https://docs.microsoft.com/powershell/module/exchange/set-policyconfig
  applicable: Security & Compliance Center
  title: Set-PolicyConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
