### YamlMime:PowershellCmdlet
summary: |-
  Get application instance for the tenant from Azure Active Directory.
module: SkypeForBusiness
notes: ""
syntaxes:
- Get-CsOnlineApplicationInstance [[-Identity] <string>] [[-ResultSize] <int>] [-Tenant <guid>] [-Force] [-WhatIf] [-Confirm]  [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsOnlineApplicationInstance -Identity appinstance01@contoso.com
  description: |-
    This example returns the application instance with identity "appinstance01@contoso.com".
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsOnlineApplicationInstance -ResultSize 10
  description: |-
    This example returns the first 10 application instances.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsOnlineApplicationInstance
  description: |-
    This example returns the details of all application instances.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The URI or the object ID of the application instance to retrieve. If this parameter is not provided, it will retrieve all application instances in the tenant.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ResultSize
  description: |+
    The result size for bulk get.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="System.Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    The Tenant ID.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
applicable:
- Skype for Business Online
uid: SkypeForBusiness.Get-CsOnlineApplicationInstance
name: Get-CsOnlineApplicationInstance
description: |-
  This cmdlet is used to get details of an application instance.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://docs.microsoft.com/powershell/module/skype/get-csonlineapplicationinstance
  applicable: Skype for Business Online
  title: Get-CsOnlineApplicationInstance
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: ""
