### YamlMime:PowershellCmdlet
summary: |-
  Indicates whether licensing information for the specified tenant is available in the Lync admin center.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Deserialized.Microsoft.Rtc.Management.WritableConfig.Settings.TenantConfiguration.TenantLicensingConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-CsTenant
  href: Get-CsTenant.yml
syntaxes:
- >-
  Get-CsTenantHybridConfiguration [-Tenant <Guid>] [[-Identity] <XdsIdentity>] [-LocalStore]

   [<CommonParameters>]
- Get-CsTenantHybridConfiguration [-Tenant <Guid>] [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsTenantLicensingConfiguration
  description: |-
    The command shown in Example 1 returns licensing configuration information for the current tenant:
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters in order to return a collection of tenant licensing configuration settings.
    Because each tenant is limited to a single, global collection of licensing configuration settings there is no need to use the Filter parameter.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Specifies the collection of tenant licensing configuration settings to be returned.
    Because each tenant is limited to a single, global collection of licensing settings there is no need include this parameter when calling the Get-CsTenantLicensingConfiguration cmdlet.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    This parameter is not used with Skype for Business Online.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Globally unique identifier (GUID) of the tenant account whose licensing settings are being returned.
    For example:

    `-Tenant "38aad667-af54-4397-aaa7-e94c79ec2308"`

    You can return your tenant ID by running this command:

    `Get-CsTenant | Select-Object DisplayName, TenantID`

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
applicable:
- Skype for Business Online
uid: SkypeForBusiness.Get-CsTenantLicensingConfiguration
name: Get-CsTenantLicensingConfiguration
description: |-
  The Get-CsTenantLicensingConfiguration cmdlet indicates whether licensing information for the specified tenant is available in the Lync admin center.
  The cmdlet returns information similar to this:

  Identity : GlobalStatus : Enabled

  If the Status is equal to Enabled then licensing information is available in the admin center.
  If not, then licensing information is not available in the admin center.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://docs.microsoft.com/powershell/module/skype/get-cstenantlicensingconfiguration
  applicable: Skype for Business Online
  title: Get-CsTenantLicensingConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: ""
